name: mydj
description: Aplikasi jurnal harian guru.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.1.2
  url_launcher: ^6.1.7
  image_picker: ^1.0.4
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Daftarkan aset gambar logo
  assets:
    - assets/images/logo_kemdikbud.png
